require("dotenv/config");
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const words = [
    {
        english: "hello",
        vietnamese: "xin chào",
        definition: "a greeting used when meeting someone",
        exampleSentence: "Hello, how are you today?",
        level: "A1",
        tags: "greeting,basic",
    },
    {
        english: "goodbye",
        vietnamese: "tạm biệt",
        definition: "used when leaving or parting",
        exampleSentence: "Goodbye, see you tomorrow!",
        level: "A1",
        tags: "greeting,basic",
    },
    {
        english: "thank you",
        vietnamese: "cảm ơn",
        definition: "an expression of gratitude",
        exampleSentence: "Thank you for your help.",
        level: "A1",
        tags: "greeting,basic",
    },
    {
        english: "please",
        vietnamese: "làm ơn",
        definition: "used for polite requests",
        exampleSentence: "Please open the door.",
        level: "A1",
        tags: "basic",
    },
    {
        english: "sorry",
        vietnamese: "xin lỗi",
        definition: "used to apologize",
        exampleSentence: "I'm sorry for being late.",
        level: "A1",
        tags: "basic",
    },
    {
        english: "water",
        vietnamese: "nước",
        definition: "a clear liquid for drinking",
        exampleSentence: "Can I have a glass of water?",
        level: "A1",
        tags: "food,basic",
    },
    {
        english: "food",
        vietnamese: "thức ăn",
        definition: "something you eat",
        exampleSentence: "The food here is delicious.",
        level: "A1",
        tags: "food,basic",
    },
    {
        english: "house",
        vietnamese: "ngôi nhà",
        definition: "a building for living in",
        exampleSentence: "I live in a small house.",
        level: "A1",
        tags: "place,basic",
    },
    {
        english: "family",
        vietnamese: "gia đình",
        definition: "a group of related people",
        exampleSentence: "My family has five members.",
        level: "A1",
        tags: "people,basic",
    },
    {
        english: "friend",
        vietnamese: "bạn bè",
        definition: "a person you like and trust",
        exampleSentence: "She is my best friend.",
        level: "A1",
        tags: "people,basic",
    },
    {
        english: "book",
        vietnamese: "quyển sách",
        definition: "a set of printed pages bound together",
        exampleSentence: "I'm reading a very interesting book.",
        level: "A1",
        tags: "object,study",
    },
    {
        english: "school",
        vietnamese: "trường học",
        definition: "a place for learning",
        exampleSentence: "I go to school every day.",
        level: "A1",
        tags: "place,study",
    },
    {
        english: "work",
        vietnamese: "làm việc",
        definition: "activity involving effort or exertion",
        exampleSentence: "I work at a technology company.",
        level: "A1",
        tags: "activity,basic",
    },
    {
        english: "money",
        vietnamese: "tiền",
        definition: "coins or notes used to buy things",
        exampleSentence: "I need some money for lunch.",
        level: "A1",
        tags: "basic",
    },
    {
        english: "time",
        vietnamese: "thời gian",
        definition: "the measured or measurable period",
        exampleSentence: "What time is it now?",
        level: "A1",
        tags: "basic",
    },
    {
        english: "morning",
        vietnamese: "buổi sáng",
        definition: "the early part of the day",
        exampleSentence: "I wake up early in the morning.",
        level: "A1",
        tags: "time,basic",
    },
    {
        english: "night",
        vietnamese: "buổi tối",
        definition: "the dark period between sunset and sunrise",
        exampleSentence: "Good night, sleep well!",
        level: "A1",
        tags: "time,basic",
    },
    {
        english: "today",
        vietnamese: "hôm nay",
        definition: "on this present day",
        exampleSentence: "Today is a beautiful day.",
        level: "A1",
        tags: "time,basic",
    },
    {
        english: "happy",
        vietnamese: "vui vẻ",
        definition: "feeling pleasure or satisfaction",
        exampleSentence: "I am very happy to see you.",
        level: "A1",
        tags: "emotion,basic",
    },
    {
        english: "big",
        vietnamese: "to, lớn",
        definition: "of great size",
        exampleSentence: "That is a very big building.",
        level: "A1",
        tags: "adjective,basic",
    },
    {
        english: "small",
        vietnamese: "nhỏ",
        definition: "of little size",
        exampleSentence: "I have a small cat.",
        level: "A1",
        tags: "adjective,basic",
    },
    {
        english: "good",
        vietnamese: "tốt",
        definition: "of high quality or standard",
        exampleSentence: "This is a good idea.",
        level: "A1",
        tags: "adjective,basic",
    },
    {
        english: "bad",
        vietnamese: "xấu, tệ",
        definition: "of poor quality",
        exampleSentence: "The weather is bad today.",
        level: "A1",
        tags: "adjective,basic",
    },
    {
        english: "hot",
        vietnamese: "nóng",
        definition: "having a high temperature",
        exampleSentence: "The coffee is too hot to drink.",
        level: "A1",
        tags: "adjective,basic",
    },
    {
        english: "cold",
        vietnamese: "lạnh",
        definition: "having a low temperature",
        exampleSentence: "It's very cold outside.",
        level: "A1",
        tags: "adjective,basic",
    },
    {
        english: "eat",
        vietnamese: "ăn",
        definition: "to put food in your mouth and swallow",
        exampleSentence: "I eat breakfast at 7 AM.",
        level: "A1",
        tags: "verb,food",
    },
    {
        english: "drink",
        vietnamese: "uống",
        definition: "to take liquid into your body",
        exampleSentence: "I drink coffee every morning.",
        level: "A1",
        tags: "verb,food",
    },
    {
        english: "sleep",
        vietnamese: "ngủ",
        definition: "to rest with eyes closed",
        exampleSentence: "I sleep eight hours every night.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "read",
        vietnamese: "đọc",
        definition: "to look at and understand written words",
        exampleSentence: "I read the newspaper every day.",
        level: "A1",
        tags: "verb,study",
    },
    {
        english: "write",
        vietnamese: "viết",
        definition: "to make letters or words on a surface",
        exampleSentence: "Please write your name here.",
        level: "A1",
        tags: "verb,study",
    },
    {
        english: "speak",
        vietnamese: "nói",
        definition: "to say words aloud",
        exampleSentence: "Can you speak English?",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "listen",
        vietnamese: "nghe",
        definition: "to pay attention to sounds",
        exampleSentence: "Listen to the teacher carefully.",
        level: "A1",
        tags: "verb,study",
    },
    {
        english: "learn",
        vietnamese: "học",
        definition: "to gain knowledge or skill",
        exampleSentence: "I want to learn English.",
        level: "A1",
        tags: "verb,study",
    },
    {
        english: "understand",
        vietnamese: "hiểu",
        definition: "to know the meaning of something",
        exampleSentence: "I don't understand this word.",
        level: "A1",
        tags: "verb,study",
    },
    {
        english: "know",
        vietnamese: "biết",
        definition: "to have information in your mind",
        exampleSentence: "I know the answer.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "want",
        vietnamese: "muốn",
        definition: "to desire or wish for",
        exampleSentence: "I want to go home.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "like",
        vietnamese: "thích",
        definition: "to find pleasant or enjoyable",
        exampleSentence: "I like watching movies.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "love",
        vietnamese: "yêu",
        definition: "to have strong affection for",
        exampleSentence: "I love my family very much.",
        level: "A1",
        tags: "verb,emotion",
    },
    {
        english: "think",
        vietnamese: "nghĩ",
        definition: "to use your mind to consider",
        exampleSentence: "I think this is correct.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "go",
        vietnamese: "đi",
        definition: "to move or travel somewhere",
        exampleSentence: "Let's go to the park.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "come",
        vietnamese: "đến",
        definition: "to move toward the speaker",
        exampleSentence: "Come here, please.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "see",
        vietnamese: "nhìn thấy",
        definition: "to perceive with the eyes",
        exampleSentence: "I can see the mountain from here.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "give",
        vietnamese: "cho, tặng",
        definition: "to hand something to someone",
        exampleSentence: "Please give me that book.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "take",
        vietnamese: "lấy",
        definition: "to get hold of something",
        exampleSentence: "Take this medicine after lunch.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "make",
        vietnamese: "làm, tạo",
        definition: "to create or produce something",
        exampleSentence: "I will make dinner tonight.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "buy",
        vietnamese: "mua",
        definition: "to get something by paying money",
        exampleSentence: "I want to buy a new phone.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "help",
        vietnamese: "giúp đỡ",
        definition: "to assist someone",
        exampleSentence: "Can you help me with this?",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "play",
        vietnamese: "chơi",
        definition: "to engage in activity for fun",
        exampleSentence: "The children play in the park.",
        level: "A1",
        tags: "verb,basic",
    },
    {
        english: "run",
        vietnamese: "chạy",
        definition: "to move quickly on foot",
        exampleSentence: "I run every morning for exercise.",
        level: "A1",
        tags: "verb,sport",
    },
    {
        english: "walk",
        vietnamese: "đi bộ",
        definition: "to move on foot at a normal pace",
        exampleSentence: "I walk to work every day.",
        level: "A1",
        tags: "verb,basic",
    },
];

async function main() {
    console.log("🌱 Seeding A1 words...");

    const user = await prisma.user.findFirst();
    if (!user) {
        console.error("No user found. Run main seed first.");
        process.exit(1);
    }

    for (const w of words) {
        const word = await prisma.word.upsert({
            where: { english: w.english },
            update: {},
            create: w,
        });

        // Create SRS card for this user
        await prisma.srsCard.upsert({
            where: { userId_wordId: { userId: user.id, wordId: word.id } },
            update: {},
            create: {
                userId: user.id,
                wordId: word.id,
                intervalDays: 0,
                easeFactor: 2.5,
                nextReview: new Date(),
                status: "new",
            },
        });
    }

    console.log(`✅ ${words.length} A1 words seeded with SRS cards`);
    console.log("🎉 Done!");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(() => prisma.$disconnect());
